language: php
php:
    - 5.5
    - 5.4
    - 5.3

before_script:
    - composer self-update && composer install

script:
    - $(pwd)/bin/phpunit

after_script:
    - $(pwd)/bin/phpcs $(pwd)/src --extensions=php --standard=PSR2
