parameters:
    gnutix_library.library_factory.xml_library_factory.class: Gnutix\StarWarsLibrary\LibraryFactory\XmlLibraryFactory
    gnutix_library.library_factory.yaml_library_factory.class: Gnutix\StarWarsLibrary\LibraryFactory\YamlLibraryFactory
    gnutix_library.twig.extension.class: Gnutix\StarWarsLibrary\Twig\Extension\GnutixStarWarsLibraryExtension
